# Generated by Django 5.2.6 on 2025-11-29 04:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('category', models.TextField()),
                ('subcategory', models.TextField(blank=True, null=True)),
                ('subject', models.TextField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('is_anonymous', models.BooleanField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'complaints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordinance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('pdf_file_path', models.TextField()),
                ('name_or_ordinance', models.TextField()),
                ('author', models.TextField(blank=True, null=True)),
                ('ordinance_number', models.TextField(blank=True, null=True)),
                ('date_of_enactment', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordinances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('service_type', models.TextField()),
                ('reference_number', models.TextField()),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('step_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_applications',
                'managed': False,
            },
        ),
    ]
