# Generated by Django 5.2.6 on 2025-11-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycebu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ordinance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serviceapplication',
            options={},
        ),
    ]
