# Generated by Django 5.2.6 on 2025-11-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycebu_app', '0003_department_emergencycontact_official'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='Official',
        ),
    ]
