# Generated by Django 5.2.6 on 2025-11-30 14:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycebu_app', '0005_department_emergencycontact_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_id', models.TextField(unique=True)),
                ('icon', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('color', models.TextField()),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('step_details', models.JSONField(blank=True, default=list, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('forms', models.JSONField(blank=True, default=list)),
                ('forms_download', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'services',
                'db_table': 'services',
            },
        ),
    ]
