# Generated by Django 5.2.6 on 2025-12-05 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycebu_app', '0006_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
