# Generated by Django 5.2.6 on 2025-12-05 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycebu_app', '0007_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='conversation_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
