# Generated by Django 5.2.6 on 2025-12-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycebu_app', '0008_chathistory_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapplication',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='document_status',
            field=models.TextField(default='pending'),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='document_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
