# Generated by Django 5.2.6 on 2025-12-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycebu_app', '0009_serviceapplication_admin_notes_and_more'),
        ('mycebu_app', '0010_auto_20251208_2354'),
    ]

    operations = [
    ]
